//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace compraOnlineWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRITO
    {
        public int Id_Carrito { get; set; }
        public int Id_Producto { get; set; }
        public int Cantidad { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
