//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace compraOnlineWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE
    {
        public int Id_Detalle { get; set; }
        public int Id_Orden { get; set; }
        public int Id_Producto { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        public decimal Importe { get; set; }
    
        public virtual ORDEN ORDEN { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
